# Generated by Django 5.0.6 on 2024-06-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='pictures/'),
        ),
    ]
